chore: add command to start environment

diff --git a/packages/socket-server/Makefile b/packages/socket-server/Makefile
--- a/packages/socket-server/Makefile
+++ b/packages/socket-server/Makefile
@@ -3,19 +3,16 @@ build:
 	pnpm run build
 
 socket-init:
-	@env_file=$${env_file:-.env.example}; \
-	echo "🚀 Building and starting Socket Server using $$env_file..."; \
-	if [ ! -f "$$env_file" ]; then echo "❌ '$$env_file' not found!" && exit 1; fi; \
-	docker-compose -f docker-compose.yml --env-file $$env_file up --build -d > /dev/null 2>&1
+	@echo "🚀 Building and starting Socket Server using .env.example..."; \
+	if [ ! -f ".env.example" ]; then echo "❌ '.env.example' not found!" && exit 1; fi; \
+	docker-compose -f docker-compose.yml --env-file .env.example up --build -d > /dev/null 2>&1
 
 socket-down:
-	@env_file=$${env_file:-.env.example}; \
-	echo "🧹 Stopping Socket Server..."; \
-	docker-compose -f docker-compose.yml --env-file $$env_file down
+	@echo "🧹 Stopping Socket Server..."; \
+	docker-compose -f docker-compose.yml --env-file .env.example down
 
 socket-wait:
-	@env_file=$${env_file:-.env.example}; \
-	. $$env_file; \
+	@. .env.example; \
 	container="$$SOCKET_NAME"; \
 	echo "⏳ Waiting for $$container to be healthy..."; \
 	until [ "$$(docker inspect -f '{{.State.Health.Status}}' $$container 2>/dev/null)" = "healthy" ]; do \
